/* Copyright 2020 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "wpe_enclave_t.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sgx_utils.h>
#include <sgx_quote.h>

#include "crypto.h"
#include "error.h"
#include "avalon_sgx_error.h"
#include "tcf_error.h"
#include "zero.h"
#include "jsonvalue.h"
#include "parson.h"
#include "hex_string.h"

#include "enclave_data.h"
#include "enclave_utils.h"
#include "signup_enclave_util.h"
#include "verify-ias-report.h"
#include "epid_signup_helper.h"
#include "dcap_signup_helper.h"

static void CreateReportDataWPE(const char* ext_data,
    const std::string& enclave_encrypt_key,
    sgx_report_data_t* report_data);

static void CreateSignupReportDataWPE(const uint8_t* ext_data,
    EnclaveData* enclave_data,
    sgx_report_data_t* report_data);

// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tcf_err_t ecall_GenerateNonce(uint8_t* out_nonce, size_t in_nonce_size) {
    tcf_err_t result = TCF_SUCCESS;
    tcf::error::ThrowIf<tcf::error::ValueError>(in_nonce_size <= 0,
        "Nonce size should be positive value");
    try {
        // Generate random bytes of size equivalent to in_nonce_size/2,
        // so that when encoded to hex string results in string of
        // size equal to in_nonce_size
        ByteArray nonce_bytes = \
            tcf::crypto::RandomBitString(in_nonce_size/2);
        // Convert nonce to hex string and persist in the EnclaveData
        EnclaveData* enclaveData = EnclaveData::getInstance();
        std::string nonce_hex = ByteArrayToHexEncodedString(nonce_bytes);
        enclaveData->set_nonce(nonce_hex);
        strncpy_s((char*)out_nonce, in_nonce_size,
            nonce_hex.c_str(), nonce_hex.length());
    } catch (tcf::error::ValueError& e) {
        Log(TCF_LOG_ERROR, "error::RandomNonce - %d - %s",
            e.error_code(), e.what());
        return TCF_ERR_CRYPTO;
    } catch (tcf::error::Error& e) {
        Log(TCF_LOG_ERROR, "error::RandomNonce - %d - %s\n",
            e.error_code(), e.what());
        return TCF_ERR_CRYPTO;
    } catch (...) {
        Log(TCF_LOG_ERROR, "error::RandomNonce - unknown internal error");
        return TCF_ERR_CRYPTO;
    }

    return result;
}  // ecall_GenerateNonce

/* Verify unique id signature obtained from KME by using unique id key.
 * Unique id signature is a digital signature computed on the hash value
 * of a concatenated string of unique id and WPE generated nonce.
 *
 * @param unique_id_key - Public key generated by KME to be
 *              used for registration
 * @param verification_key_signature - digital signature computed on
 *              hash of concatenated string of unique id and nonce
 */
tcf_err_t ecall_VerifyUniqueIdSignature(const char* unique_id_key,
    const char* verification_key_signature) {

    tcf_err_t result = TCF_SUCCESS;
    try {
        tcf::error::ThrowIfNull(unique_id_key, "Unique ID is null");
        tcf::error::ThrowIfNull(verification_key_signature,
            "Verification key signature is null");

        ByteArray verify_key_hex_bytes = HexEncodedStringToByteArray(
            unique_id_key);
        std::string b64_verify_key = ByteArrayToStr(verify_key_hex_bytes);
        tcf::crypto::sig::PublicKey public_key(b64_verify_key);

        EnclaveData* enclave_data = EnclaveData::getInstance();
        // compute hash on b64 encoded verification key and nonce hex string
        std::string concat_str = b64_verify_key + enclave_data->get_nonce();
        ByteArray hash = tcf::crypto::ComputeMessageHash(
            StrToByteArray(concat_str));
        size_t status = public_key.VerifySignature(hash,
            HexEncodedStringToByteArray(verification_key_signature));
        // VerifySignature returns 1 on success,
        // 0 on failure and -1 in case of error
        if (status != 1) {
            result = TCF_ERR_VALUE;
        }
    } catch (tcf::error::Error& e) {
        SAFE_LOG(TCF_LOG_ERROR,
            "Error in ecall_VerifyUniqueIdSignature: %04X -- %s",
            e.error_code(), e.what());
        ocall_SetErrorMessage(e.what());
        result = e.error_code();
    } catch (...) {
        SAFE_LOG(TCF_LOG_ERROR,
            "Unknown error in Avalon enclave(ecall_VerifyUniqueIdSignature)");
        result = TCF_ERR_UNKNOWN;
    }
    return result;
}  // ecall_VerifyUniqueIdSignature

// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tcf_err_t ecall_CreateSignupDataWPE(const sgx_target_info_t* inTargetInfo,
    const uint8_t* inExtData,
    size_t inExtDataSize,
    const uint8_t* inExtDataSig,
    size_t inExtDataSigSize,
    const uint8_t* inKmeAttestation,
    size_t inKmeAttestationSize,
    char* outPublicEnclaveData,
    size_t inAllocatedPublicEnclaveDataSize,
    sgx_report_t* outEnclaveReport) {
    tcf_err_t result = TCF_SUCCESS;

    try {
        tcf::error::ThrowIfNull(inTargetInfo, "Target info pointer is NULL");
        tcf::error::ThrowIfNull(inExtData, "Extended data is NULL");
        tcf::error::ThrowIf<tcf::error::ValueError>(inExtDataSize == 0,
            "Extended data size shouldn't be zero");
        // Disable this check for now, will enable it once we have
        // proper value in inExtDataSig
        /* tcf::error::ThrowIfNull(inExtDataSig,
            "Extended data signature input is NULL");*/
        tcf::error::ThrowIfNull(outPublicEnclaveData,
            "Public enclave data pointer is NULL");
        tcf::error::ThrowIfNull(outEnclaveReport,
            "Intel SGX report pointer is NULL");

        Zero(outPublicEnclaveData, inAllocatedPublicEnclaveDataSize);

        // Get instance of enclave data
        EnclaveData* enclaveData = EnclaveData::getInstance();

        /*
           TODO: Implement Verify extended data signature using
           KME Verifying key
        */

        ByteArray ext_data_bytes(inExtData, inExtData+inExtDataSize);
        enclaveData->set_extended_data(ext_data_bytes);

        tcf::error::ThrowIf<tcf::error::ValueError>(
            inAllocatedPublicEnclaveDataSize < enclaveData->get_public_data_size(),
            "Public enclave data buffer size is too small");

        // Create the report data we want embedded in the enclave report.
        sgx_report_data_t reportData = {0};
        CreateSignupReportDataWPE(inExtData, enclaveData, &reportData);

        sgx_status_t ret = sgx_create_report(
            inTargetInfo, &reportData, outEnclaveReport);
        tcf::error::ThrowSgxError(ret, "Failed to create enclave report");
        // Give the caller a copy of the signing and encryption keys
        strncpy_s(outPublicEnclaveData, inAllocatedPublicEnclaveDataSize,
            enclaveData->get_public_data().c_str(),
            enclaveData->get_public_data_size());

    } catch (tcf::error::Error& e) {
        SAFE_LOG(TCF_LOG_ERROR,
            "Error in Avalon enclave(ecall_CreateSignupDataWPE): %04X -- %s",
            e.error_code(), e.what());
        ocall_SetErrorMessage(e.what());
        result = e.error_code();
    } catch (...) {
        SAFE_LOG(TCF_LOG_ERROR,
            "Unknown error in Avalon enclave(ecall_CreateSignupDataWPE)");
        result = TCF_ERR_UNKNOWN;
    }

    return result;
}  // ecall_CreateSignupDataWPE

// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
void CreateSignupReportDataWPE(const uint8_t* ext_data,
    EnclaveData* enclave_data, sgx_report_data_t* report_data) {

    // We will put the following in the report data
    // WPE_ENCLAVE:  REPORT_DATA[0:31] - PUB ENC KEY
    //               REPORT_DATA[32:63] - EXT DATA where EXT_DATA contains
    //               verification key generated by KME
    
    // WARNING - WARNING - WARNING - WARNING - WARNING - WARNING - WARNING
    //
    // If anything in this code changes the way in which the actual enclave
    // report data is represented, the corresponding code that verifies
    // the report data has to be change accordingly.
    //
    // WARNING - WARNING - WARNING - WARNING - WARNING - WARNING - WARNING

    std::string enclave_encrypt_key = \
        enclave_data->get_serialized_encryption_key();

    // NOTE - we are putting the hash directly into the report
    // data structure because it is (64 bytes) larger than the SHA256
    // hash (32 bytes) but we zero it out first to ensure that it is
    // padded with known data.

    Zero(report_data, sizeof(*report_data));

    uint8_t enc_key_hash[SGX_HASH_SIZE] = {0};
    uint8_t ext_data_hash[SGX_HASH_SIZE] = {0};
    ComputeSHA256Hash(enclave_encrypt_key, enc_key_hash);
    ComputeSHA256Hash((const char*) ext_data, ext_data_hash);

    // Concatenate hash of public encryption key and hash of extended data
    memcpy(report_data->d, enc_key_hash, SGX_HASH_SIZE);
    memcpy((report_data->d) + SGX_HASH_SIZE, ext_data_hash, SGX_HASH_SIZE);

}  // CreateSignupReportDataWPE

// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tcf_err_t ecall_VerifyEnclaveInfoWPEEpid(const char* enclave_info,
    const char* mr_enclave, const char* ext_data) {
    tcf::error::ThrowIfNull(ext_data, "Extended data is NULL");

    tcf_err_t result = TCF_SUCCESS;
    EpidSignupHelper signup_helper;
    result = signup_helper.verify_enclave_info(enclave_info, mr_enclave);

    // Verify Report Data by comparing hash of report data in
    // Verification Report with computed report data
    sgx_report_data_t computed_report_data = {0};
    CreateReportDataWPE(ext_data,
        signup_helper.get_enclave_encryption_key(), &computed_report_data);

    //Compare computedReportData with expectedReportData
    sgx_report_data_t expected_report_data = signup_helper.get_report_data();
    tcf::error::ThrowIf<tcf::error::ValueError>(
        memcmp(computed_report_data.d, expected_report_data.d,
        SGX_REPORT_DATA_SIZE)  != 0,
        "Invalid Report data: computedReportData does not match expectedReportData");
    return result;
}  // ecall_VerifyEnclaveInfoWPEEpid

// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tcf_err_t ecall_VerifyEnclaveInfoWPEDcap(const char* enclave_info,
    const char* mr_enclave, const char* ext_data) {
    tcf::error::ThrowIfNull(ext_data, "Extended data is NULL");

    tcf_err_t result = TCF_SUCCESS;
    DcapSignupHelper signup_helper;
    result = signup_helper.verify_enclave_info(enclave_info, mr_enclave);

    tcf::error::ThrowIf<tcf::error::ValueError>(
        result != TCF_SUCCESS,
        "Trusted enclave info verification failed");
    // Verify Report Data by comparing hash of report data in
    // Verification Report with computed report data
    sgx_report_data_t computed_report_data = {0};
    CreateReportDataWPE(ext_data,
        signup_helper.get_enclave_encryption_key(), &computed_report_data);

    //Compare computedReportData with expectedReportData
    sgx_report_data_t expected_report_data = signup_helper.get_report_data();
    tcf::error::ThrowIf<tcf::error::ValueError>(
        memcmp(computed_report_data.d, expected_report_data.d,
        SGX_REPORT_DATA_SIZE)  != 0,
        "Invalid Report data: computedReportData does not match expectedReportData");
    return result;
}  // ecall_VerifyEnclaveInfoWPEDcap

// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
void CreateReportDataWPE(const char* ext_data,
    const std::string& enclave_encrypt_key,
    sgx_report_data_t* report_data) {
    // We will put the following in the report data
    // WPE_ENCLAVE:  REPORT_DATA[0:31] - PUB ENC KEY
    //               REPORT_DATA[32:63] - EXT DATA where EXT_DATA contains
    //               verification key generated by KME

    // NOTE - we are putting the hash directly into the report
    // data structure because it is (64 bytes) larger than the SHA256
    // hash (32 bytes) but we zero it out first to ensure that it is
    // padded with known data.

    Zero(report_data, sizeof(*report_data));

    uint8_t enc_key_hash[SGX_HASH_SIZE] = {0};
    uint8_t ext_data_hash[SGX_HASH_SIZE] = {0};
    ComputeSHA256Hash(enclave_encrypt_key, enc_key_hash);
    ComputeSHA256Hash(ext_data, ext_data_hash);

    // Concatenate hash of public encryption key and hash of extended data

    memcpy(report_data->d, enc_key_hash, SGX_HASH_SIZE);
    memcpy((report_data->d) + SGX_HASH_SIZE, ext_data_hash, SGX_HASH_SIZE);

}  // CreateReportDataWPE
