# Copyright 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.5'

services:
  avalon-blockchain-connector:
    container_name: avalon-blockchain-connector-eth
    image: avalon-blockchain-connector-eth-dev
    build:
      context: .
      dockerfile: ./blockchain_connector/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    command: |
      bash -c "
        avalon_blockchain_connector -b ethereum -u http://avalon-listener:1947
        tail -f /dev/null
        "
    volumes:
      - ./:/project/avalon
    depends_on:
      - avalon-listener
      - avalon-enclave-manager

networks:
  default:
    external:
      name: ganache_local_net
