# Copyright 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.5'

services:
  avalon-enclave-manager:
    image: avalon-sgx-enclave-manager-dev
    build:
      context: .
      dockerfile: ./enclave_manager/Dockerfile
      args:
        - SGX_MODE=HW
        - ATTESTATION_TYPE=dcap
    devices:
      - "/dev/sgx:/dev/sgx"
    depends_on:
      - avalon-pccs
    command: |
      bash -c "
        if [ -v CLEAN_SEALED_DATA ] && [ $CLEAN_SEALED_DATA = 1 ]; then rm -f /project/avalon/.sealed/.sealed.data*; fi;
        sleep 5s
        enclave_manager --lmdb_url http://avalon-lmdb:9090
        tail -f /dev/null
      "   
  avalon-pccs:
    container_name: avalon-pccs
    image: avalon-pccs-server-dev
    build:
      context: .
      dockerfile: ./docker/pccs/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - DISTRO=$DISTRO
        # Pass DCAP PCCS API key
        - API_KEY=$API_KEY
    expose:
      - 8081
    command: |
      bash -c "
        node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js        
        tail -f /dev/null
      "
