version: '3.5'
services:
  #
  # node1 is first of the two-node ethereum private network based on Hyperledger Besu
  #
  node1.avalon.local:
    image: hyperledger/besu:1.4.3
    command: >-
      --data-path=/var/lib/besu --genesis-file=/var/lib/besu/genesis.json --rpc-http-enabled 
      --rpc-http-host=0.0.0.0 --rpc-ws-enabled --rpc-ws-host=0.0.0.0 --discovery-enabled=false 
      --p2p-host=0.0.0.0 --rpc-http-api=ETH,NET,WEB3,DEBUG,MINER,ADMIN,TXPOOL,CLIQUE 
      --rpc-ws-api=ETH,NET,WEB3,DEBUG,MINER,ADMIN,TXPOOL,CLIQUE --rpc-http-cors-origins='*' 
      --host-whitelist='*' --min-gas-price=0
    ports:
      - 22011:8545
      # websocket endpoint (for subscribing to events)
      - 22002:8546
    volumes:
      - './besu/node1:/var/lib/besu'
    networks:
      local_net:
        ipv4_address: '172.13.0.2'

  #
  # ethsigner1 is the signing wallet associated to node1, and provides an RPC endpoint for web3 APIs
  # The signing account is 0x7085d4d4c6efea785edfba5880bb62574e115626
  #
  rpc.node1.avalon.local:
    image: pegasyseng/ethsigner:0.4.0
    command: >-
      --chain-id=12345 --downstream-http-host=node1.avalon.local --downstream-http-port=8545
      --http-listen-host=0.0.0.0 --http-listen-port=8555 file-based-signer 
      --password-file=/var/lib/ethsigner/password.txt --key-file=/var/lib/ethsigner/keystore/account.txt
    ports:
      - 22001:8555
    volumes:
      - './ethsigner/node1:/var/lib/ethsigner'
    depends_on:
      - node1.avalon.local
    networks:
      local_net:
        ipv4_address: '172.13.0.3'

  #
  # node2 is the second of the two-node ethereum private network based on Hyperledger Besu
  #
  node2.avalon.local:
    image: hyperledger/besu:1.4.3
    command: >-
      --data-path=/var/lib/besu --genesis-file=/var/lib/besu/genesis.json --rpc-http-enabled 
      --rpc-http-host=0.0.0.0 --rpc-ws-enabled --rpc-ws-host=0.0.0.0 --discovery-enabled=false 
      --p2p-host=0.0.0.0 --rpc-http-api=ETH,NET,WEB3,DEBUG,MINER,ADMIN,TXPOOL,CLIQUE 
      --rpc-ws-api=ETH,NET,WEB3,DEBUG,MINER,ADMIN,TXPOOL,CLIQUE --rpc-http-cors-origins='*' 
      --host-whitelist='*' --min-gas-price=0
    ports:
      - 23011:8545
      # websocket endpoint (for subscribing to events)
      - 23002:8546
    volumes:
      - './besu/node2:/var/lib/besu'
    depends_on:
      - node1.avalon.local
    networks:
      local_net:
        ipv4_address: '172.13.0.4'

  #
  # ethsigner2 is a 2nd signing wallet associated to node1, and provides an RPC endpoint for web3 APIs
  # The signing account is 0xb36b1934004385bfa5c51eaecb8ec348ec733ca8
  #
  rpc.node2.avalon.local:
    image: pegasyseng/ethsigner:0.4.0
    command: >-
      --chain-id=12345 --downstream-http-host=node2.avalon.local --downstream-http-port=8545
      --http-listen-host=0.0.0.0 --http-listen-port=8555 file-based-signer 
      --password-file=/var/lib/ethsigner/password.txt --key-file=/var/lib/ethsigner/keystore/account.txt
    ports:
      - 23001:8555
    volumes:
      - './ethsigner/node2:/var/lib/ethsigner'
    depends_on:
      - node2.avalon.local
    networks:
      local_net:
        ipv4_address: '172.13.0.5'

networks:
  local_net:
    name: besu_local_net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16

