server:
  port: ${EEA_WORKER_PORT:18091}

worker:
  name: ${EEA_WORKER_NAME:customWorker}
  organizationId: ${EEA_WORKER_ORGID:0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff}
  applicationTypeIds: ${EEA_WORKER_APPTYPEID:[0x1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f]}
  registryListContractAddress: ${EEA_REGISTRYLIST_CONTRACT_ADDRESS:}
  registryContractAddress: ${EEA_REGISTRY_CONTRACT_ADDRESS:0x79ede703f6e4FFbb50a3b7798CfEBF792581E830}
  workOrderContractAddress: ${EEA_WORKORDER_CONTRACT_ADDRESS:0x9B04867c5551EC3b5aa9EB1496DdC79EE0e95ECb}
  detailsFilePath: ${EEA_WORKER_DETAILS_PATH:./src/main/resources/worker-details.json}
  workerBaseDir: ${EEA_WORKER_BASE_DIR:/tmp/eea-worker}
  gasPriceMultiplier: ${EEA_GAS_PRICE_MULTIPLIER:1.3} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
  gasPriceCap: ${EEA_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap
  blockchainNodeAddress: ${EEA_WORKER_BLOCKCHAIN_NODE_ADDRESS:http://localhost:8545}


wallet:
  encryptedFilePath: ${EEA_WORKER_WALLET_PATH:./src/main/resources/wallet/wallet1.json}
  password: ${EEA_WORKER_WALLET_PASSWORD:whatever}

management:
  endpoint:
    restart:
      enabled: true