.TH "/home/dano/git/avalon/common/cpp/crypto/SAVE Directory Reference" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/cpp/crypto/SAVE Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBverify_certificate\&.h\fP"
.br
.ti -1c
.RI "file \fBverify_signature\&.h\fP"
.br
.in -1c
