.TH "_sgx_errlist_t" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sgx_errlist_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sgx_status_t \fBerr\fP"
.br
.ti -1c
.RI "const char * \fBmsg\fP"
.br
.ti -1c
.RI "const char * \fBsug\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
