.TH "avalon_sdk.http_client.http_jrpc_client.HttpJrpcClient" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.http_client.http_jrpc_client.HttpJrpcClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, url)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBServiceURL\fP"
.br
.ti -1c
.RI "\fBProxyHandler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to handle HTTP JSON RPC communication by the client.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
