.TH "avalon_sdk.connector.blockchains.ethereum.ethereum_listener.BlockchainInterface" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.connector.blockchains.ethereum.ethereum_listener.BlockchainInterface
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, config)"
.br
.ti -1c
.RI "def \fBnewListener\fP (self, contract, event, fromBlock='latest')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Ethereum blockchain interface to event processor.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def avalon_sdk\&.connector\&.blockchains\&.ethereum\&.ethereum_listener\&.BlockchainInterface\&.newListener ( self,  contract,  event,  fromBlock = \fC'latest'\fP)"

.PP
.nf
Create a filter to get events from latest block by default.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
