.TH "avalon_sdk.connector.blockchains.fabric.base.ClientBase" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.connector.blockchains.fabric.base.ClientBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBavalon_sdk\&.connector\&.blockchains\&.fabric\&.event_listener\&.EventListener\fP, and \fBavalon_sdk\&.connector\&.blockchains\&.fabric\&.tx_committer\&.TxCommitter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, profile, channel_name, org_name, peer_name, user_name)"
.br
.ti -1c
.RI "def \fBchannel_name\fP (self)"
.br
.ti -1c
.RI "def \fBchannel\fP (self)"
.br
.ti -1c
.RI "def \fBorg_name\fP (self)"
.br
.ti -1c
.RI "def \fBpeer_name\fP (self)"
.br
.ti -1c
.RI "def \fBuser_name\fP (self)"
.br
.ti -1c
.RI "def \fBuser\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for a Hyperledger Fabric client.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
