.TH "avalon_sdk.registry.registry_status.RegistryStatus" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.registry.registry_status.RegistryStatus
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBACTIVE\fP = 1"
.br
.ti -1c
.RI "int \fBOFF_LINE\fP = 2"
.br
.ti -1c
.RI "int \fBDECOMMISSIONED\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Worker registry status values:
1 - registry is ACTIVE
2 - registry is temporarily OFF_LINE
3 - registry is DECOMMISSIONED

From EEA spec 5.2.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
