.TH "avalon_sdk.connector.direct.jrpc.jrpc_work_order_receipt.JRPCWorkOrderReceiptImpl" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.connector.direct.jrpc.jrpc_work_order_receipt.JRPCWorkOrderReceiptImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits WorkOrderReceipt\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, config)"
.br
.ti -1c
.RI "def \fBwork_order_receipt_create\fP (self, work_order_id, worker_service_id, worker_id, requester_id, receipt_create_status, work_order_request_hash, requester_nonce, requester_signature, signature_rules, receipt_verification_key, id=None)"
.br
.ti -1c
.RI "def \fBwork_order_receipt_update\fP (self, work_order_id, updater_id, update_type, update_data, update_signature, signature_rules, id=None)"
.br
.ti -1c
.RI "def \fBwork_order_receipt_retrieve\fP (self, work_order_id, id=None)"
.br
.ti -1c
.RI "def \fBwork_order_receipt_update_retrieve\fP (self, work_order_id, updater_id, update_index, id=None)"
.br
.ti -1c
.RI "def \fBwork_order_receipt_lookup\fP (self, worker_service_id=None, worker_id=None, requester_id=None, receipt_status=None, id=None)"
.br
.ti -1c
.RI "def \fBwork_order_receipt_lookup_next\fP (self, last_lookup_tag, worker_service_id=None, worker_id=None, requester_id=None, receipt_status=None, id=None)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class is an implementation of WorkOrderReceiptInterface
to manage work order receipts from the client side.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def avalon_sdk\&.connector\&.direct\&.jrpc\&.jrpc_work_order_receipt\&.JRPCWorkOrderReceiptImpl\&.work_order_receipt_create ( self,  work_order_id,  worker_service_id,  worker_id,  requester_id,  receipt_create_status,  work_order_request_hash,  requester_nonce,  requester_signature,  signature_rules,  receipt_verification_key,  id = \fCNone\fP)"

.PP
.nf
Create a Work Order Receipt JSON RPC request and submit to an
Avalon listener.

Parameters:
work_order_id            Work order ID
worker_service_id        Worker service ID
worker_id                Worker ID value derived from the worker's DID
requester_id             Requester ID
receipt_create_status    Receipt creation status
work_order_request_hash  Work order request hash value
requester_nonce          Requester generated nonce
requester_signature      Signature generated by the requester
signature_rules          Defines hashing and signing algorithms;
                 separated by forward slash '/'
receipt_verification_key Receipt verification key
id                       Optional JSON RPC request ID

.fi
.PP
 
.SS "def avalon_sdk\&.connector\&.direct\&.jrpc\&.jrpc_work_order_receipt\&.JRPCWorkOrderReceiptImpl\&.work_order_receipt_lookup ( self,  worker_service_id = \fCNone\fP,  worker_id = \fCNone\fP,  requester_id = \fCNone\fP,  receipt_status = \fCNone\fP,  id = \fCNone\fP)"

.PP
.nf
Work Order Receipt Lookup
All fields are optional and, if present, condition should match for
all fields. If none are passed it should return all
work order receipts.

Parameters:
worker_service_id        Optional worker service ID to lookup
worker_id                Optional worker ID value derived from
                 the worker's DID
requester_id             Optional requester ID to lookup
receipt_status           Optional receipt status
id                       Optional JSON RPC request ID

.fi
.PP
 
.SS "def avalon_sdk\&.connector\&.direct\&.jrpc\&.jrpc_work_order_receipt\&.JRPCWorkOrderReceiptImpl\&.work_order_receipt_lookup_next ( self,  last_lookup_tag,  worker_service_id = \fCNone\fP,  worker_id = \fCNone\fP,  requester_id = \fCNone\fP,  receipt_status = \fCNone\fP,  id = \fCNone\fP)"

.PP
.nf
Work Order Receipt Lookup Next.
Call to retrieve subsequent results after calling
work_order_receipt_lookup or

Parameters:
last_lookup_tag          Last lookup tag returned by
                 work_order_receipt_lookup
worker_service_id        Optional worker service ID to lookup
worker_id                Optional worker ID value derived from
                 the worker's DID
requester_id             Optional requester ID to lookup
receipt_status           Optional receipt status
id                       Optional JSON RPC request ID

.fi
.PP
 
.SS "def avalon_sdk\&.connector\&.direct\&.jrpc\&.jrpc_work_order_receipt\&.JRPCWorkOrderReceiptImpl\&.work_order_receipt_retrieve ( self,  work_order_id,  id = \fCNone\fP)"

.PP
.nf
Retrieve a work order receipt JSON RPC request and submit to an
Avalon listener.

Parameters:
work_order_id Work order ID
id            Optional Optional JSON RPC request ID

.fi
.PP
 
.SS "def avalon_sdk\&.connector\&.direct\&.jrpc\&.jrpc_work_order_receipt\&.JRPCWorkOrderReceiptImpl\&.work_order_receipt_update ( self,  work_order_id,  updater_id,  update_type,  update_data,  update_signature,  signature_rules,  id = \fCNone\fP)"

.PP
.nf
Update a Work Order Receipt JSON RPC request and submit an
Avalon listener.

Parameters:
work_order_id    Work Order ID
updater_id       Updater ID
update_type      Updater type
update_data      Receipt update data
update_signature Signature of the update
signature_rules  Defines hashing and signing algorithms;
         separated by forward slash '/'
id               Optional JSON RPC request ID

.fi
.PP
 
.SS "def avalon_sdk\&.connector\&.direct\&.jrpc\&.jrpc_work_order_receipt\&.JRPCWorkOrderReceiptImpl\&.work_order_receipt_update_retrieve ( self,  work_order_id,  updater_id,  update_index,  id = \fCNone\fP)"

.PP
.nf
Retrieve a work order receipt update JSON RPC request and submit to an
Avalon listener.

Parameters:
work_order_id Work order ID
id            Optional Optional JSON RPC request ID

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
