.TH "avalon_sdk.work_order_receipt.work_order_receipt.WorkOrderReceiptRequest" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.work_order_receipt.work_order_receipt.WorkOrderReceiptRequest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBcreate_receipt\fP (self, wo_request, receipt_create_status, signing_key, nonce=None)"
.br
.ti -1c
.RI "def \fBupdate_receipt\fP (self, work_order_id, update_type, update_data, signing_key)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsig_obj\fP"
.br
.ti -1c
.RI "\fBSIGNING_ALGORITHM\fP"
.br
.ti -1c
.RI "\fBHASHING_ALGORITHM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to create work order receipt APIs such as
create, update, retrieve, and lookup.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def avalon_sdk\&.work_order_receipt\&.work_order_receipt\&.WorkOrderReceiptRequest\&.create_receipt ( self,  wo_request,  receipt_create_status,  signing_key,  nonce = \fCNone\fP)"

.PP
.nf
Create a work order receipt corresponding to a workorder ID.

Parameters:
wo_request            JSON RPC work order request used to create the
              work order request as defined in EEA spec 6.1.1
receipt_create_status Receipt creation status
signing_key           Private key of the signer
nonce                 Optional random number or monotonic counter

Returns:
JSON RPC request of type dictionary

.fi
.PP
 
.SS "def avalon_sdk\&.work_order_receipt\&.work_order_receipt\&.WorkOrderReceiptRequest\&.update_receipt ( self,  work_order_id,  update_type,  update_data,  signing_key)"

.PP
.nf
Update the existing work order receipt with
update_type and update_data.

Parameters:
work_order_id Work order ID whose receipt
      needs to be updated
update_type   Update type. These values correspond to
      receipt status as defined in EEA Spec 7.1.1
update_data   Update-specific data that depends on
      the workOrderStatus
Returns:
JSON RPC work order update receipt request of type dictionary

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
