.TH "avalon_sdk.worker.worker_details.WorkerStatus" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.worker.worker_details.WorkerStatus
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBACTIVE\fP = 1"
.br
.ti -1c
.RI "int \fBOFF_LINE\fP = 2"
.br
.ti -1c
.RI "int \fBDECOMMISSIONED\fP = 3"
.br
.ti -1c
.RI "int \fBCOMPROMISED\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Worker status values:
1 - worker is ACTIVE
2 - worker is temporarily OFF_LINE
3 - worker is DECOMMISSIONED
4 - worker is COMPROMISED

From EEA spec 5.2.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
