.TH "avalon_sdk.worker.worker_details.WorkerType" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
avalon_sdk.worker.worker_details.WorkerType
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTEE_SGX\fP = 1"
.br
.ti -1c
.RI "int \fBMPC\fP = 2"
.br
.ti -1c
.RI "int \fBZK\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Worker types are:
1 = TEE-SGX: Intel SGX Trusted Execution Environment (hardware based)
2 = MPC: Trusted Multi-Party Compute (software/hardware based)
3 = ZK: Zero-knowledge proofs (software based)

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
