.TH "/home/dano/git/avalon/common/sgx_workload/iohandler/file_io.cpp" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/sgx_workload/iohandler/file_io.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'file_io\&.h'\fP
.br
\fC#include 'iohandler_enclave\&.h'\fP
.br
\fC#include 'enclave_utils\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_FILE_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_IO_RESULT_SIZE\fP   128"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFileIoExecutor\fP C++ class implementation for Avalon Inside-Out File I/O\&. To use, #include 'file_io\&.h' 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
