.TH "JsonValue" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonValue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonValue\fP (\fBJSON_Value\fP *value=nullptr)"
.br
.ti -1c
.RI "\fBoperator JSON_Value *\fP ()"
.br
.ti -1c
.RI "\fBoperator const JSON_Value *\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBJSON_Value\fP * \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
