.TH "/home/dano/git/avalon/common/cpp/jsonvalue.h" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/cpp/jsonvalue.h
.SH SYNOPSIS
.br
.PP
\fC#include 'packages/parson/parson\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJsonValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Avalon JSON object extraction utilities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
