.TH "md__home_dano_git_avalon_common_cpp_BUILD" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_dano_git_avalon_common_cpp_BUILDBUILD 
 \- 
.SH "Building the common libraries"
.PP
.PP
Make sure you have environment variables \fCSGX_SDK\fP and \fCSGX_SSL\fP defined (see \&.\&./\&.\&./\&.\&./BUILD\&.md 'BUILD\&.md') and then run 
.PP
.nf
mkdir build
cd build
cmake \&.\&. -G "Unix Makefiles" && make

.fi
.PP
 
