.TH "/home/dano/git/avalon/common/cpp/crypto/sig_private_key.h" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/cpp/crypto/sig_private_key.h
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ec\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtcf::crypto::sig::PrivateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Avalon ECDSA private key functions: generation, serialization, and signing\&. ECDSA used for Secp256k1 elliptical curves\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
