.TH "StringArray" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringArray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.PP
Inherits vector< char >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringArray\fP (const std::string &value)"
.br
.ti -1c
.RI "\fBStringArray\fP (const size_t size)"
.br
.ti -1c
.RI "void \fBassign\fP (const std::string &value)"
.br
.ti -1c
.RI "std::string \fBstr\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector type for containing printable characters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
