.TH "tcf::error::Error" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcf::error::Error
.SH SYNOPSIS
.br
.PP
.PP
Inherits runtime_error\&.
.PP
Inherited by \fBtcf::error::CryptoError\fP, \fBtcf::error::DivisionByZero\fP, \fBtcf::error::IndexError\fP, \fBtcf::error::IOError\fP, \fBtcf::error::MemoryError\fP, \fBtcf::error::OverflowError\fP, \fBtcf::error::RuntimeError\fP, \fBtcf::error::SystemBusyError\fP, \fBtcf::error::SystemError\fP, \fBtcf::error::UnknownError\fP, \fBtcf::error::ValueError\fP, and \fBtcf::error::WorkloadError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBError\fP (\fBtcf_err_t\fP in_error, const std::string &msg)"
.br
.ti -1c
.RI "\fBtcf_err_t\fP \fBerror_code\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
