.TH "tcf::error::ValueError" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcf::error::ValueError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtcf::error::Error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueError\fP (const std::string &msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
