.TH "test_ethereum_worker_registry_list_impl.TestEthereumWorkerRegistryListImpl" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_ethereum_worker_registry_list_impl.TestEthereumWorkerRegistryListImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, config_file)"
.br
.ti -1c
.RI "def \fBtest_registry_add\fP (self)"
.br
.ti -1c
.RI "def \fBtest_registry_update\fP (self)"
.br
.ti -1c
.RI "def \fBtest_registry_set_status\fP (self)"
.br
.ti -1c
.RI "def \fBtest_registry_lookup\fP (self)"
.br
.ti -1c
.RI "def \fBtest_registry_retrieve\fP (self)"
.br
.ti -1c
.RI "def \fBtest_registry_lookup_next\fP (self)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
