.TH "/home/dano/git/avalon/common/cpp/utils.cpp" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/cpp/utils.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'types\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBStrToByteArray\fP (std::string str)"
.br
.ti -1c
.RI "std::string \fBByteArrayToStr\fP (\fBByteArray\fP ba)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Avalon ByteArray and String conversion utilities\&. 
.SH "Function Documentation"
.PP 
.SS "std::string ByteArrayToStr (\fBByteArray\fP ba)"
Convert a ByteArray vector to a C++ string\&. 
.SS "\fBByteArray\fP StrToByteArray (std::string str)"
Convert a C++ string to a ByteArray vector\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
