.TH "/home/dano/git/avalon/common/sgx_workload/workload/work_order_data.h" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/sgx_workload/workload/work_order_data.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtcf::WorkOrderData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines class \fBtcf::WorkOrderData\fP for work order data submitted to workload processors\&. To use, #include 'work_order_data\&.h' 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
