.TH "/home/dano/git/avalon/common/cpp/zero.h" 3 "Wed May 6 2020" "Version 0.5.0.dev1" "Hyperledger Avalon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dano/git/avalon/common/cpp/zero.h
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'c11_support\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBZero\fP (T &v)"
.br
.ti -1c
.RI "template<typename T > void \fBZeroV\fP (std::vector< T > &v)"
.br
.ti -1c
.RI "void \fBZero\fP (void *v, size_t length)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Avalon zero initialization utilities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperledger Avalon from the source code\&.
