apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmdb
  template:
    metadata:
      name: lmdb
      labels:
        app: lmdb
    spec:
      containers:
      - image: tcf-dev:latest
        name: lmdb-server
        imagePullPolicy: Never
        envFrom:
        - prefix: TCF_
          configMapRef:
            name: tcf-config
        command: ["/bin/bash"]
        args: ["$(TCF_HOME)/scripts/lmdb.sh"]
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: db
          mountPath: /lmdb
      volumes:
      - name: db
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lmdb
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: lmdb
