apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsname
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  selector: 
    matchLabels:
      type: nfs
