apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsname
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.1.0.7   # nfs-server IP
    path: /export
