token_validation: token_validation.cpp execution_logic.cpp
	g++ -Wall -Wno-write-strings token_validation.cpp execution_logic.cpp -o token_validation -I.

.PHONY: clean
clean :
	-rm -rf token_validation
